import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
        style={{
          backgroundColor: "lightblue",
          padding: "1rem",
          
        }}
        >
          <ul
            style={{
              display: "flex",
              listStyleType: "none",
              padding: 0,
              margin: 0,
            }}
          >
            <li style={{ marginRight: "1rem" }}>Home</li>
            <li style={{ marginRight: "1rem" }}>Login</li>
            <li>Sign up</li>
          </ul>        
            </header>
        {children}
        
       
      </body>
    </html>
  );
}
